var body = document.body;
var container = document.createElement('div');
container.classList.add('container', 'my-5');
var divCategory = document.createElement('div');
divCategory.classList.add('main', 'p-4', 'shadow-sm');
body.appendChild(container);
container.appendChild(divCategory);
var h4 = document.createElement('h4');
var textH4 = document.createTextNode('Categorías');
divCategory.appendChild(h4);
h4.appendChild(textH4);
var form = document.createElement('form');
form.classList.add('d-flex');
var div = document.createElement('div');
var label = document.createElement('label');
label.textContent = "Nombre";
var input = document.createElement('input');
divCategory.appendChild(form);
form.appendChild(div);
div.appendChild(label);
div.appendChild(input);
var btn = document.createElement('button');
btn.classList.add('btn', 'btn-primary');
btn.textContent = "Agregar";
form.appendChild(btn);
