var body = document.body;
var container = document.createElement('div');
container.classList.add('container', 'my-5', 'p-0');
var divReports = document.createElement('div');
divReports.classList.add('p-4', 'shadow-sm');
body.appendChild(container);
container.appendChild(divReports);
var h2 = document.createElement('h2');
var textH2 = document.createTextNode('Reportes');
divReports.appendChild(h2);
h2.appendChild(textH2);
// Tabla 1 - Resumen
var titleTable1 = document.createElement('h4');
var textTitleTable1 = document.createTextNode('Resumen');
var table1 = document.createElement('table');
table1.classList.add('table');
var tBodyTable1 = document.createElement('tbody');
// tr1
var trTable1 = document.createElement('tr');
var td1 = document.createElement('td');
var textTd1 = document.createTextNode('Categoría con mayor ganancia');
var td2 = document.createElement('td');
var textTd2 = document.createTextNode('Comida');
var td3 = document.createElement('td');
var textTd3 = document.createTextNode('+$200');
divReports.appendChild(titleTable1);
titleTable1.appendChild(textTitleTable1);
divReports.appendChild(table1);
table1.appendChild(tBodyTable1);
tBodyTable1.appendChild(trTable1);
trTable1.appendChild(td1);
trTable1.appendChild(td2);
trTable1.appendChild(td3);
td1.appendChild(textTd1);
td2.appendChild(textTd2);
td3.appendChild(textTd3);
// tr1
var trTable2 = document.createElement('tr');
var td4 = document.createElement('td');
var textTd4 = document.createTextNode('Categoría con mayor gasto');
var td5 = document.createElement('td');
var textTd5 = document.createTextNode('Comida');
var td6 = document.createElement('td');
var textTd6 = document.createTextNode('+$200');
tBodyTable1.appendChild(trTable2);
trTable2.appendChild(td4);
trTable2.appendChild(td5);
trTable2.appendChild(td6);
td4.appendChild(textTd4);
td5.appendChild(textTd5);
td6.appendChild(textTd6);
// tr3
var trTable3 = document.createElement('tr');
var td7 = document.createElement('td');
var textTd7 = document.createTextNode('Categoría con mayor balance');
var td8 = document.createElement('td');
var textTd8 = document.createTextNode('Comida');
var td9 = document.createElement('td');
var textTd9 = document.createTextNode('+$200');
tBodyTable1.appendChild(trTable3);
trTable3.appendChild(td7);
trTable3.appendChild(td8);
trTable3.appendChild(td9);
td7.appendChild(textTd7);
td8.appendChild(textTd8);
td9.appendChild(textTd9);
// tr4
var trTable4 = document.createElement('tr');
var td10 = document.createElement('td');
var textTd10 = document.createTextNode('Mes con mayor ganancia');
var td11 = document.createElement('td');
var textTd11 = document.createTextNode('Comida');
var td12 = document.createElement('td');
var textTd12 = document.createTextNode('+$200');
tBodyTable1.appendChild(trTable4);
trTable4.appendChild(td10);
trTable4.appendChild(td11);
trTable4.appendChild(td12);
td10.appendChild(textTd10);
td11.appendChild(textTd11);
td12.appendChild(textTd12);
// tr5
var trTable5 = document.createElement('tr');
var td13 = document.createElement('td');
var textTd13 = document.createTextNode('Mes con mayor gasto');
var td14 = document.createElement('td');
var textTd14 = document.createTextNode('Comida');
var td15 = document.createElement('td');
var textTd15 = document.createTextNode('+$200');
tBodyTable1.appendChild(trTable5);
trTable5.appendChild(td13);
trTable5.appendChild(td14);
trTable5.appendChild(td15);
td13.appendChild(textTd13);
td14.appendChild(textTd14);
td15.appendChild(textTd15);
// Table 2 - Total por categorías
var titleTable2 = document.createElement('h4');
var textTitleTable2 = document.createTextNode('Total por categorías');
var table2 = document.createElement('table');
table2.classList.add('table');
var tHeadTable2 = document.createElement('thead');
var th1 = document.createElement('th');
var textTh1 = document.createTextNode('Categoría');
var th2 = document.createElement('th');
var textTh2 = document.createTextNode('Ganancias');
var th3 = document.createElement('th');
var textTh3 = document.createTextNode('Gastos');
var th4 = document.createElement('th');
var textTh4 = document.createTextNode('Balance');
divReports.appendChild(titleTable2);
titleTable2.appendChild(textTitleTable2);
divReports.appendChild(table2);
table2.appendChild(tHeadTable2);
tHeadTable2.appendChild(th1);
tHeadTable2.appendChild(th2);
tHeadTable2.appendChild(th3);
tHeadTable2.appendChild(th4);
th1.appendChild(textTh1);
th2.appendChild(textTh2);
th3.appendChild(textTh3);
th4.appendChild(textTh4);
var tBodyTable2 = document.createElement('tbody');
// tr6
var trTable6 = document.createElement('tr');
var td16 = document.createElement('td');
var textTd16 = document.createTextNode('Comida');
var td17 = document.createElement('td');
var textTd17 = document.createTextNode('+$200');
var td18 = document.createElement('td');
var textTd18 = document.createTextNode('-$1200');
var td19 = document.createElement('td');
var textTd19 = document.createTextNode('$200');
table2.appendChild(tBodyTable2);
tBodyTable2.appendChild(trTable6);
trTable6.appendChild(td16);
trTable6.appendChild(td17);
trTable6.appendChild(td18);
trTable6.appendChild(td19);
td16.appendChild(textTd16);
td17.appendChild(textTd17);
td18.appendChild(textTd18);
td19.appendChild(textTd19);
